export { PizzasPage } from './PizzasPage'
export { DrinksPage } from './DrinksPage'
export { PromosPage } from './PromosPage'
export { ContactsPage } from './ContactsPage'
export { CartPage } from './CartPage'
export { ProfilePage } from './ProfilePage'
export { ErrorPage } from './ErrorPage'
